baseURL = 'https://michaelcrubenstein.github.io/brookline-mbta-compliance-site/'
languageCode = 'en-us'
title = 'Brookline Compliance With The MBTA Community Act'
theme = 'mbtaca'
[params]
  version = '1.0'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

