baseURL = 'https://michaelcrubenstein.github.io/brookline-mbta-compliance-site'
languageCode = 'en-us'
title = 'Brookline Compliance With The MBTA Community Act'
theme = 'mbtaca'
[params]
  version = '1.0'
  google = 'google9e5a09349208fc21.html'

[[menu.main]]
name = "Home"
url = "/brookline-mbta-compliance-site/"
weight = 1

[[menu.main]]
name = "About"
url = "/brookline-mbta-compliance-site/about/"
weight = 2

